on:
  push:
    branches: [main]

jobs:
  build:
    if: github.repository != 'grepsedawk/template'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install Crystal
        uses: crystal-lang/install-crystal@v1.6.0

      - name: Install Lucky
        run: |
          cd /tmp
          git clone https://github.com/luckyframework/lucky_cli
          cd lucky_cli
          git checkout $(git describe --tags $(git rev-list --tags --max-count=1))
          shards install
          shards build
          mv bin/lucky /usr/local/bin/

      - name: Build
        run: |
          only_repo=$(echo $GITHUB_REPOSITORY | cut -d'/' -f2)
          new_snek_name=$(echo $only_repo | sed 's/-/_/g')

          echo "Removing build specific files"
          rm -f .github/workflows/build.yml

          echo "🔮Initializing via: lucky init"
          lucky init.custom $new_snek_name

          echo "Merging template with lucky init"
          cp $new_snek_name/README.md .
          cp -rn $new_snek_name/* .
          cp -rn $new_snek_name/.?* .
          rm -rf $new_snek_name/

          echo "Adding ameba to shard.yml"
          sed -i '/^development_dependencies:/i \ \ ameba:\n\ \ \ \ github: crystal-ameba/ameba' shard.yml

          echo "Fixing ameba violation 😳"
          # TODO: Remove after https://github.com/luckyframework/lucky_cli/pull/739 is released
          sed -i '49,58d' config/server.cr

      - name: Push Built Tempalte
        run: |
          git add .
          git commit --amend --no-edit
          git push -f
